[package]
name = "reels-macros"
version = "0.0.1"
edition = "2021"
authors = ["Mark Zhang <markintoshzzz@gmail.com>"]
description = "Helper macros for reels"
license = "MIT"
readme = "README.md"

# [dependencies]

